source 'https://rubygems.org'

gem 'rails'
gem 'sqlite3'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'devise'
gem 'paperclip'
gem 'bootstrap-sass'
gem 'searchkick'
gem 'ai4r'
gem 'byebug'
gem 'faker'
gem 'kmeans-clusterer'
